### ISSUE TITLE
webmin h5ai

### ISSUE THREAD

**Issue by 2dan** [Aniverse/inexistence#19]
webmin h5ai 可不可以加个开关，或者默认不安装

**Comment by Aniverse** [comment]
webmin 其实我就在想弄成默认不安装的。。。
h5ai 不行。我倒是想知道你为什么不想要 h5ai……

**Comment by 2dan** [comment]
> webmin 其实我就在想弄成默认不安装的。。。
> h5ai 不行。我倒是想知道你为什么不想要 h5ai……

用脚本就为了一键安装PT软件，能下载种子刷上传就可以了。很多时候只需要安装一个qb就可以 了。要这些花哨的功能没用。安装软件越多越占系统资源。

**Comment by Aniverse** [comment]
![一时语塞](https://github.com/Aniverse/emoticon/raw/master/1/%E4%B8%80%E6%97%B6%E8%AF%AD%E5%A1%9E.jpg) emmm……
这两个是你看得到的，在你看不到的地方其实我的脚本还装了很多估计你觉得没用的东西

**Comment by 2dan** [comment]
好吧，我也只是随口一提。其实影响也不大。还是很感谢提供这个脚本，很方便。也很强大。

**Comment by sulf1ron** [comment]
h5ai 只是一些 PHP 文件，并不在后台运行占用性能
