### ISSUE TITLE
建议修改默认缓存参数

### ISSUE THREAD

**Issue by lionheart2133** [Aniverse/inexistence#20]
**环境：ovh家的盒子，内存4G，系统debian 8**

在使用这个脚本以后一直存在一个问题，就是在我用flexget把种子都添加进去之后，使用top发现软件系统占达到了120%，目前看来是磁盘I/O占用，但是之前不知道，困扰了我两天，以为是客户端和内核的兼容问题，然而占用高的同时，系统也变得实在太卡了，没什么debug的心思，于是期间换了这个脚本的deluge/qbit/rtorrent，也尝试过换内核，都没什么改善，甚至怀疑过是脚本的问题

### 今天自己编译从官方源编译安装了deluge，系统占用仍然达到了75%，胡乱改设置的时候，动了一下cache，size设置为65536，time设置为30，然后就一切正常了

这是非常好用的一个一键包，希望作者能够修改相关配置

**Comment by Aniverse** [comment]
我脚本安装 Deluge 带了 ltconfig 插件并默认启用了 High Performance Seed (HPS)。HPS 预设的 `cache_size` 就是 65536，`cache_expiry` 就是 30。ltconfig 会覆盖 deluge 的设置，所以我想理论上脚本装完后应该就是 65536+30 的参数（你在设置的 cache 里看到的参数是 deluge 的设置，但这里的值会被 ltconfig 覆盖）
