### ISSUE TITLE
大佬能否增加Deluge1.3.9跳过效验版本，谢谢

### ISSUE THREAD

**Issue by sunpma** [Aniverse/inexistence#22]
别的站点都支持1.3.15版本，唯独FRDS只能用1.3.9，又主要是转种FRDS的资源，实在是有点麻烦，大佬看能不能加上一个Deluge1.3.9跳过效验的版本呢？万分感谢！

**Comment by Aniverse** [comment]
没这个打算。1.3.15 支持跳过校验的版本我迟早也会去掉的（等 Deluge 2.0 正式发布且广泛被 PT 站支持后）
现在 FRDS 支持 qb 了，比较神奇的是 Deluge 1.3.15 还不支持，再继续观察观察
用 1.3.9 也实在是因为某些国内站不支持（HD4FANS、TCCF 应该还不支持 1.3.9 以上吧），没办法的办法，唉
