### ISSUE TITLE
希望添加filemananger（或许能代替h5ai）

### ISSUE THREAD

**Issue by mylovesaber** [Aniverse/inexistence#28]
隔壁n1小钢炮固件自带filemananger，我用过感觉功能多，好用，能在线视频能上传能下载文件夹都能下载，h5ai好像和nginx建立文件索引差不多，功能似乎差了些，不知老哥可否考虑添加下filemananger？随手找了个介绍差别的仅供参考，https://blog.csdn.net/yoshinomm/article/details/79310137

**Comment by Aniverse** [comment]
这阵子尽量看看，看了下官方安装脚本好像很简单的样子
我这人经常懒癌发作，to do list 的事情懒得搞什么的……

**Comment by mylovesaber** [comment]
>听说过你懒癌发作哈哈，全套简明安装教程给你准备好了我家用盒子已经用上了，你直接添加到脚本里面替换ha5i就行了：

### 安装filebrowser
#### 安装fb
`curl -fsSL https://filebrowser.xyz/get.sh | bash`

#### 配置fb
1. 创建配置数据库：
`filebrowser -d /etc/filebrowser.db config init`

2. 设置监听地址：
`filebrowser -d /etc/filebrowser.db config set --address 192.168.0.28`
这里ip地址填写你路由器界面看到的你server的内网ip地址，盒子的话直接填写盒子的ip地址即可

3. 设置监听端口：
`filebrowser -d /etc/filebrowser.db config set --port 9999`
自行修改一个没用过的端口号

4. 设置语言环境：
`filebrowser -d /etc/filebrowser.db config set --locale zh-cn`

5. 设置日志位置：
`filebrowser -d /etc/filebrowser.db config set --log /var/log/filebrowser.log`

6. 添加一个用户：
`filebrowser -d /etc/filebrowser.db users add root password --perm.admin`
其中的root和password分别是自行设定的用户名和密码，根据自己的需求更改。

添加自启动服务：
`vim /lib/systemd/system/filebrowser.service`
填入：
```
[Unit]
Description=File Browser
After=network.target

[Service]
ExecStart=/usr/local/bin/filebrowser -d /etc/filebrowser.db

[Install]
WantedBy=multi-user.target
```
保存退出。

运行服务：
`systemctl start filebrowser.service`

开机启动服务：
`systemctl enable filebrowser.service`

查看服务运行状态：
`systemctl status filebrowser.service`

输入并运行fb：
`filebrowser -d /etc/filebrowser.db`
到此所有安装配置就结束了

还需要配置https的话看这里：https://www.mivm.cn/filebrowser/

**Comment by mylovesaber** [comment]
另外你在ttg还是哪个群我见过你艾特过我给过你这脚本链接，github有时不能及时回复，方便告知下你群昵称吗？

**Comment by Aniverse** [comment]
不是我还能是谁啊……

**Comment by Warm-rain** [comment]
@mylovesaber debian9 运行服务报错Failed to start filebrowser.service: Unit filebrowser.service is not loaded properly: Invalid argument.
See system logs and 'systemctl status filebrowser.service' for details.
查看服务状态错误：● filebrowser.service - File Browser
   Loaded: error (Reason: Invalid argument)
   Active: inactive (dead)

Mar 02 15:05:57 dedi-par-125708 systemd[1]: [/lib/systemd/system/filebrowser.service:5] Unknown section 'Se
Mar 02 15:05:57 dedi-par-125708 systemd[1]: filebrowser.service: Service lacks both ExecStart= and ExecStop
Mar 02 15:06:05 dedi-par-125708 systemd[1]: [/lib/systemd/system/filebrowser.service:5] Unknown section 'Se
Mar 02 15:06:05 dedi-par-125708 systemd[1]: filebrowser.service: Service lacks both ExecStart= and ExecStop
Mar 02 15:09:53 dedi-par-125708 systemd[1]: [/lib/systemd/system/filebrowser.service:5] Unknown section 'Se
Mar 02 15:09:53 dedi-par-125708 systemd[1]: filebrowser.service: Service lacks both ExecStart= and ExecStop
Mar 02 15:18:38 dedi-par-125708 systemd[1]: [/lib/systemd/system/filebrowser.service:6] Unknown lvalue 'Exe
Mar 02 15:18:38 dedi-par-125708 systemd[1]: filebrowser.service: Service lacks both ExecStart= and ExecStop
Warning: filebrowser.service changed on disk. Run 'systemctl daemon-reload' to reload units.
lines 1-13/13 (END)
这是不支持？我按着操作试了好多次了

**Comment by mylovesaber** [comment]
> @mylovesaber debian9 运行服务报错Failed to start filebrowser.service: Unit filebrowser.service is not loaded properly: Invalid argument.
> See system logs and 'systemctl status filebrowser.service' for details.
> 查看服务状态错误：● filebrowser.service - File Browser
> Loaded: error (Reason: Invalid argument)
> Active: inactive (dead)
> 
> Mar 02 15:05:57 dedi-par-125708 systemd[1]: [/lib/systemd/system/filebrowser.service:5] Unknown section 'Se
> Mar 02 15:05:57 dedi-par-125708 systemd[1]: filebrowser.service: Service lacks both ExecStart= and ExecStop
> Mar 02 15:06:05 dedi-par-125708 systemd[1]: [/lib/systemd/system/filebrowser.service:5] Unknown section 'Se
> Mar 02 15:06:05 dedi-par-125708 systemd[1]: filebrowser.service: Service lacks both ExecStart= and ExecStop
> Mar 02 15:09:53 dedi-par-125708 systemd[1]: [/lib/systemd/system/filebrowser.service:5] Unknown section 'Se
> Mar 02 15:09:53 dedi-par-125708 systemd[1]: filebrowser.service: Service lacks both ExecStart= and ExecStop
> Mar 02 15:18:38 dedi-par-125708 systemd[1]: [/lib/systemd/system/filebrowser.service:6] Unknown lvalue 'Exe
> Mar 02 15:18:38 dedi-par-125708 systemd[1]: filebrowser.service: Service lacks both ExecStart= and ExecStop
> Warning: filebrowser.service changed on disk. Run 'systemctl daemon-reload' to reload units.
> lines 1-13/13 (END)
> 这是不支持？我按着操作试了好多次了

你试试安装隔壁荒野无灯老哥魔改过的fb试试，他做了全平台魔改。这软件本质就是下载下来改权限设置好初始的一些设置就可以启动了。他github帐号被永封，码云能找到他。
全新安装无灯的集成dplayer和其他各种魔改的filebrowser：
```
cd /tmp &&wget http://files.80x86.io/router/rom/opt/fb/filebrowser_linux_amd64
mv filebrowser_linux_amd64 /usr/local/bin/filebrowser &&chmod 0755 /usr/local/bin/filebrowser
filebrowser config init
filebrowser config set --address 内网ip或者服务器ip
filebrowser config set --port 端口号比如9999
filebrowser config set --locale zh-cn
filebrowser config set --log /var/log/filebrowser.log
filebrowser users add 管理员账户名 密码 --perm.admin
```

无灯的改版filebrowser启动时默认同目录下会生成数据库，需要和原版filebrowser一样配置一下，只是几个配置命令中所有的 **/etc/filebrowser.db** 都要删除掉。

然后启动fb：
`filebrowser -d /usr/local/bin/filebrowser.db`

添加自启动服务：
`vim /lib/systemd/system/filebrowser.service`
填入：

```
[Unit]
Description=File Browser
After=network.target

[Service]
ExecStart=/usr/local/bin/filebrowser -d /usr/local/bin/filebrowser.db

[Install]
WantedBy=multi-user.target
```

保存退出。

运行：
`systemctl start filebrowser.service`

开机启动：
`systemctl enable filebrowser.service`

查看运行状态：
`systemctl status filebrowser.service`

tip:更新无灯的filebrowser只需全新安装fb全命令的前两条即下载-改名-覆盖-改权限，之后重启服务即可：
`systemctl restart filebrowser.service`

我是ubuntu18.04，所有操作基于此，你debian的话得看看debian下服务建立方式和路径是不是和ubuntu是一样的，别一味复制粘贴

**Comment by Aniverse** [comment]
已经懒得没救了我。。。
后来试了下感觉确实还可以，但是我感觉我是真的近期不想碰 seedbox／vps／dedicated server／shell scripts 啥的（虽然每天还花了不少时间在这方面或者在聊这方面的 QQ 群里），啥时候加上我也不知道了。。。。

**Comment by Aniverse** [comment]
咕咕了一年后终于加上了
