### ISSUE TITLE
libtorrent-rasterbar安装错误

### ISSUE THREAD

**Issue by sunpma** [Aniverse/inexistence#29]
02) libtorrent-rasterbar 1.1.12 (RC_1_1 branch)
03) libtorrent-rasterbar 1.2.0  (RC_1_2 branch)
30) Select another version
Which version do you want? (Default 02): 30

 ATTENTION  Make sure to input the correct version
 Here is a list of all the available versions

Input the version you want: libtorrent-rasterbar 1.0.11.0

选择自定义libtorrent-rasterbar没有选择列表了，
手动输入libtorrent-rasterbar 1.0.11.0或libtorrent-rasterbar1.0.11后安装错误，
qb和de都不能使用....试了好几次都不行.libtorrent-rasterbar1.2以上版本总是崩溃..

**Comment by Aniverse** [comment]
你的 qb 是不是选的 4.1.4 以及更高版本的？如果是的话，lt 1.0.11 在我所知范围内是无法成功编译出 qb 4.1.4 以后的版本的，所以我脚本当你选择了 qb 4.1.4 及以后的版本的时候直接不出现 1.0.11 的选项

**Comment by Aniverse** [comment]
不出列表的问题……恩确实是最近出现的，我就说我咋记得我哪个地方忘记改了，迟点修复下

**Comment by Aniverse** [comment]
后来直接去掉了自定义 libtorrent 的选项（因为太容易出 bug，不同版本 lt 对 de/qb 不同版本的兼容性普通用户可能也搞不清楚，更重要是的现在基本上没有用低于 1.1.13/14 版本的 1.1.X 版本或者低于 1.0.11 的 1.0.X 版本的必要，且 1.2 版本还存在一些 1.1 中没有的 bug。如有需要，这部分用户一般自己也知道如何编译）
因此这个就 closed 了
