### ISSUE TITLE
您好，大佬.

### ISSUE THREAD

**Issue by ywyha** [Aniverse/inexistence#3]
首先非常感谢提供这么易用简单的一键脚本，万分感谢。

webmin是否可以选择是否安装呢？

期待大佬解答，谢谢大佬。

**Comment by ywyha** [comment]
您好，大佬，限速脚本能否增加下载限速功能，谢谢大佬……

**Comment by Aniverse** [comment]
【1】【webmin】
现在脚本运行时问下来的问题已经够多了，webmin 不是很想再问一遍了……考虑有些功能改成安装完以后再输入命令来安装，类似 QuickBox 的 `box install`，不过仅仅是考虑阶段，做起来我还有点嫌麻烦_(:з」∠)_ （虽然我就是 Ctrl+C 的……）
因为是用 rtinst 脚本带的 rtwebmin 装的，所以默认装了rt才会装这个（默认装的原因是我觉得装一个反正也很快并且一般来说没什么坏处……），不装rt就没有
（嘛，直接把rtwebmin拿出来也行啦……）
总结一下就是……我不是很想再增加选择是否安装 webmin，因为感觉不是很有必要……
---------------------------------------------------
【2】【限速下载】
说句实话我连 iptables、tc 都不会用的……什么时候我会用这些东西了我会加上去的

**Comment by ywyha** [comment]
谢谢大佬回复的这么详细，明白webmin的问题啦，这个脚本如此简化的操作方式真的太方便啦。真的很感谢大佬提供这么简单易用的脚本。

因为刚折腾盒子那会给我折腾坏啦……因为从没有接触过linux命令式的操作方式，脑袋根本一时半会是用不了从图形化操作转换到命令操作的方式……VI是啥 nano是啥，版本是啥，debian是啥 ubuntu是啥SSH是啥，端口是啥，webui是啥这些东西简直是一股脑的塞进了我的脑子里，别提有多蒙圈了……每样东西我都要去了解下是什么才能进行下一步……就好比，我问别人2是什么，别人告诉我1+1就等于2啊，可是当时我却连1是什么都不知道…………

至于为什么不想装webmin，可能因为我太矫情了吧……因为之前没用过这个东西，多装个之前没用过的东西，有点强迫症的感觉，不过无所谓啦。其他东西，我都觉得很好用，吼吼……虽然刚装上webmin有点蒙圈，（没见过这东西哇……）但是看了下webmin里边的东西，现在觉得也是很不错哒，功能很多的样子。（虽然里边的大部分东西我都不知道做啥用的） 

再一个明明做出了其他很多人都觉得好用的东西，却还是如此的谦逊，低调，偶真是打心底里佩服的。

再次膜拜大佬，再次感谢大佬。

**Comment by Aniverse** [comment]
我也不是谦虚，算不上大佬……我之前都不想宣传脚本的主要原因就是觉得写得太烂了不好意思（现在觉得无所谓了，烂就烂吧）
盒子嘛只要你愿意折腾很多东西用久了就会了，这个脚本也就是经验的产物罢了
