### ISSUE TITLE
建议增加Deluge的umask值设置

### ISSUE THREAD

**Issue by Rhilip** [Aniverse/inexistence#31]
默认情况下Deluge的umask值为644，即对于使用Deluge下载的文件权限为`rw-r--r--`。
而Deluge以root用户启动，不利于op、online这样使用非root用户登录ssh移动、删除的情况
建议增加默认UMask值为 000 或其他合适值。

文档： https://dev.deluge-torrent.org/wiki/UserGuide/Service/systemd#DelugeDaemondelugedService

**Comment by Aniverse** [comment]
感谢建议，已改。qb/flexget/tr 的也改了下  

以前也有人和我说过这个问题（rutorrent 的 filemanager 无法删除 de/qb 下载的文件），我当时想着是什么时候把  deluge 的运行改成普通用户，做成类似 QuickBox 的多用户，但是一直懒得动……（其实我不知道 UMask 这个东西←_←）

最近懒／烦死了，现在才处理，抱歉
