### ISSUE TITLE
建议换成阿里云源

### ISSUE THREAD

**Issue by duxphp** [Aniverse/inexistence#32]
建议换成阿里云源 de源太慢了

**Comment by Aniverse** [comment]
1. 我也有这个想法（参考 superupdate.sh）并打算实施，换源和升级系统打算做成单独的脚本，然后在安装脚本里再调用。
但是我懒癌犯了。。。上上个星期这个东西弄了一点，然后就没碰过了。。。
现在懒／烦得一笔，巴不得把  VPS、seedbox、PT 啥的全都抛在脑后。。。

2. 目前换的源在欧美的服务器上测试起来速度都不错……亚洲的我就不知道了。主要是一般也就国外的服务器会用这脚本，所以我原先想到过可能会有速度慢的问题不过没管那么多

**Comment by duxphp** [comment]
给一个选择源的选项   因为想在自己家里的小服务器安装一个下载机系统

**Comment by SuTree** [comment]
最好在脚本开始的时候手动选择一下 服务器所在地 做个ping值统计给出最优 国外跟国内的网络环境差别很大  ubuntu官方的自动选择源貌似还行 没研究是怎么实现的

**Comment by Aniverse** [comment]
> 最好在脚本开始的时候手动选择一下 服务器所在地 做个ping值统计给出最优 国外跟国内的网络环境差别很大 ubuntu官方的自动选择源貌似还行 没研究是怎么实现的

给出最优这个我实在是懒得做了，估计有人做过类似的。并且我在脚本里做这个测试会大幅增加跑脚本的时间。  
我加一个换源的选项，主要是为了应对某些独服／VPS 商家，用控制面板装的系统自带的镜像源有点问题，不怎么好用的情况。  
嫌脚本给的源慢，你可以选择自己先换一个速度快的，然后脚本里选择不换源就是了。  

另外本脚本主要面对的用户是使用欧美独立服务器的中国大陆用户……在非欧美机器上使用起来如何我不怎么考虑。实际上我在我的 NAS 上也跑过这个脚本，速度是真的慢……我家里的网络从 GitHub 和 SourceForge 下载都非常慢。。。。

**Comment by SuTree** [comment]
> > 最好在脚本开始的时候手动选择一下服务器所在地做个ping值统计给出最优国外跟国内的网络环境差别很大ubuntu官方的自动选择源貌似还行没研究是怎么实现的
> 
> 给出最优这个我实在是懒得做了，估计有人做过类似的。并且我在脚本里做这个测试会大幅增加跑脚本的时间。
> 我加一个换源的选项，主要是为了应对某些独服／VPS商家，用控制面板装的系统自带的镜像源有点问题，不怎么好用的情况。
> 嫌脚本给的源慢，你可以选择自己先换一个速度快的，然后脚本里选择不换源就是了。
> 
> 另外本脚本主要面对的用户是使用欧美独立服务器的中国大陆用户……在非欧美机器上使用起来如何我不怎么考虑。实际上我在我的NAS 上也跑过这个脚本，速度是真的慢……我家里的网络从GitHub 和SourceForge 下载都非常慢。。。。

说起爬github就是泪。。。
加个阿里挺好的，加个选项就行吧，别搞那么复杂。

**Comment by Aniverse** [comment]
我现在想了下，就算把镜像源换成国内的，脚本在国内的安装速度大概率还是很慢，因为很多软件源码是从 GitHub、SourceForge 等网站获取的，这类网站没梯子速度也很慢，还不如直接开代理跑脚本。因此这个先不改了
