### ISSUE TITLE
安装qb及de后监控文件夹设置无效

### ISSUE THREAD

**Issue by SayaBear** [Aniverse/inexistence#33]
RT
OP 19o机器，debian 9，安装rt 0.9.6，qb 4.1.5，de 1.3.15，全程安装未报错
然后设置qb和de的监控目录时，qb报`无法保存程序偏好选项，可能是无法连接到qBttorrent`，de设置之后重新打开preference对话框又回到默认文件夹
使用chmod对整个/home文件夹赋权无效
请教如何解决这一问题……

PS.Hetzner 23o机器测试，Ubuntu 18.04，出现同样问题
怀疑是自己某个环节没有设置正确……

**Comment by Aniverse** [comment]
本菜鸡也不知道这是什么情况……
如果你或者谁知道了的话请告诉我
