### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by TyrielWW** [Aniverse/inexistence#39]
Debian 9.0 和  ubuntu 18.04，安装不上，装到一半报错退出
报错信息：
Setting up atop (2.4.0-3) ...
ls: cannot access '/var/log/atop/atop_*': No such file or directory
Created symlink /etc/systemd/system/multi-user.target.wants/atop.service -> /lib/systemd/system/atop.service.
Created symlink /etc/systemd/system/multi-user.target.wants/atopacct.service -> /lib/systemd/system/atopacct.service.
Job for atopacct.service failed because a timeout was exceeded.
See "systemctl status atopacct.service" and "journalctl -xe" for details.
invoke-rc.d: initscript atopacct, action "start" failed.
* atopacct.service - Atop process accounting daemon
   Loaded: loaded (/lib/systemd/system/atopacct.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Mon 2019-05-06 11:34:48 CST; 5ms ago
     Docs: man:atopacctd(8)
  Process: 3519 ExecStart=/usr/sbin/atopacctd (code=exited, status=0/SUCCESS)

May 06 11:33:18 PT systemd[1]: Starting Atop process accounting daemon...
May 06 11:33:18 PT atopacctd[3521]: Version: 2.4.0 - 2019/01/12 20:37:57  <gerlof.langeveld@atoptool.nl>
May 06 11:33:18 PT atopacctd[3519]: receive NETLINK family, errno -2
May 06 11:34:48 PT systemd[1]: atopacct.service: Start operation timed out. Terminating.
May 06 11:34:48 PT systemd[1]: atopacct.service: Failed with result 'timeout'.
May 06 11:34:48 PT systemd[1]: Failed to start Atop process accounting daemon.
dpkg: error processing package atop (--configure):
 installed atop package post-installation script subprocess returned error exit status 1

Debian 8.0 可以安装，但是安装后qb和deluge无法启动
安装过程中会有个选择
Setting up systemd (215-17+deb8u11) ...
Configuration file '/etc/systemd/system.conf'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** system.conf (Y/I/N/O/D/Z) [default=N] ? 
无论选择什么都可以安装结束，但是都无法启动

**Comment by TyrielWW** [comment]
忘了说了，我用的是hetzner德国机房的机器，装proxmox开的虚拟机。
现在装的是ubuntu 16.04，只装deluge，可以使用，qb装不上。

**Comment by Aniverse** [comment]
说实话我也不知道是什么情况……

**Comment by TyrielWW** [comment]
没关系，我只是报备一下，现在ubuntu16.04+deluge可以用，回头我再开个虚拟机，单独装qb测试

**Comment by cokan** [comment]
安装怎么感觉是碰运气啊  有时候可以装上  有时候就失败

**Comment by cokan** [comment]
到底哪个系统哪个版本成功率最高呢？

**Comment by Aniverse** [comment]
现在再回头看一下这个问题。QQ群里有人和我反应 OpenVZ 的 VPS 装 atop 就会出现问题
所以我现在干脆检测到非独服和非 KVM 架构的 VPS 直接提示脚本可能出问题……

**Comment by Aniverse** [comment]
> 到底哪个系统哪个版本成功率最高呢？

报错请和楼主一样，带上日志。（出错的话脚本会告诉你如何查看日志）

我只能说，Debian 8-10，Ubuntu 16.04/18.04，我作为脚本作者需要做测试，每个系统我起码装了好几十遍的，总共装了几百遍是肯定有的，我没感觉到什么系统容易装成功什么系统更容易失败。反正我现在自己装下来基本上都不会有问题，只要我自己碰到了问题我都会想办法修复的。

至于其他人碰到了问题，往往由于信息的缺失我无法判断问题所在。就好比你去找医生诊断，只告诉医生你肚子痛，在缺少更进一步的信息之前医生也无法做出判断（比如你之前吃了些什么东西）
或者就是本贴的情况，楼主给了信息，但由于庸医（我）技术不佳也无法判断情况。不过目前我的感觉是信息不足问题更大一些。
