### ISSUE TITLE
jietu 命令能否少截几张

### ISSUE THREAD

**Issue by wqzvic88** [Aniverse/inexistence#41]
jietu命令能否少截几张，皮也只是要3张而已，高清的还好，碰到原盘截个10张图，等好久啊。能否截个3-5张就行。

**Comment by Aniverse** [comment]
因为有的截图可能不太好用所以才截10张保险起见
以后可能会加个设置截几张图（在脚本代码里改）

**Comment by Aniverse** [comment]
刚更新了下 jietu 脚本，现在可以修改脚本第 12 行来指定每次截图多少张
```
pics=10
```

默认还是 10，嫌多的话自己改一下就行了

更新 jietu 命令的方法（root 下）：
```
wget -qO /usr/local/bin/jietu https://github.com/Aniverse/inexistence/raw/master/00.Installation/script/jietu && chmod +x /usr/local/bin/jietu
```
