### ISSUE TITLE
向星大求问 iso格式原盘的bdinfo

### ISSUE THREAD

**Issue by wqzvic88** [Aniverse/inexistence#42]
有一个iso格式的原盘，我想要bdinfo
1. 使用了guazai的命令
得到：
已将 /home/XXX/qbittorrent/download/Pitch Perfect 2012 UHD Blu-Ray EUR 2160p HEVC DTS-HD MA 7.1-CHDBits/Pitch Perfect 2012 UHD Blu-Ray EUR 2160p HEVC DTS-HD MA 7.1-CHDBits.iso 以只读模式挂载到 /etc/inexistence/06.BluRay/Pitch.Perfect.2012.UHD.Blu-Ray.EUR.2160p.HEVC.DTS-HD.MA.7.1-CHDBits

2. bdinfo guazai的目录， 提示错误，错误命令如下：
Please wait while we scan the disc...
An error occurred while scanning the stream clip file 00000.CLPI.
The disc may be copy-protected or damaged.

和guazai的是只读模式有关么？怎么才能Bdinfo, iso格式的原盘呢。

**Comment by Aniverse** [comment]
bdinfo 那个脚本里使用的 bdinfocli 程序不支持 UHD BD（我也不打算更新，有点故意分开的意思）
要扫 UHD BD 的 bdinfo 请用 `bluray` 脚本
不过有的情况下也会出问题，我也无能为力
