### ISSUE TITLE
请求更新mktorrent到1.1版本

### ISSUE THREAD

**Issue by Bintel** [Aniverse/inexistence#43]
mktorrent 1.1版本已经发布2年了, 请求更新
https://github.com/Rudde/mktorrent/releases

**Comment by Aniverse** [comment]
知道，但其实我是故意不更新的……
我自己基本不用 mktorrent，不过很早以前有人和我反应 1.1 速度比 1.0 还慢并且不显示制作进度，所以我就把 1.1 的编译给注释掉了，然后最近又直接把这些注释的给删掉了

**Comment by Bintel** [comment]
了解了, 谢谢回复
