### ISSUE TITLE
星大，zuozhong命令能否调整块尺寸大小呢？

### ISSUE THREAD

**Issue by wqzvic88** [Aniverse/inexistence#44]
星大，zuozhong命令没有调整尺寸大小的命令么？一般是没问题的话，但是在PTP，偶尔有一些做出的种用不了，PTP提示“The piece size of 16 MiB (2^24 ~170 pieces) is not within limits. It must be 1 MiB (2^20 ~2711 pieces) to 8 MiB (2^23 ~339 pieces)”
注：这个1M到8M不是固定的，资源太大的话会4M到16M，但不管资源什么大小，块尺寸4M是都可以覆盖，要不然以后把默认的尺寸调整成4M？

**Comment by Aniverse** [comment]
之前有人和我说过这事情，我不知道为什么 PTP 要限制到 8M。实际上我用 16M 已经是在考虑兼容性了，不考虑兼容性我就上 32M 甚至 128M 了
脚本你可以自己改，我目前不打算改

**Comment by Aniverse** [comment]
蛋疼，刚想着去加这个自定义区块的功能，才发现原来我自己都忘了，其实我以前已经加了一个指定区块大小的功能了 emmm

用法：
```
zuozhong 目标文件 区块大小
```

区块大小不写的情况下，默认是 24，也就是 2 的 24 次方（16,777,216=16M）
你要用 4M 区块，就输入 22，也就是 `zuozhong 目标文件 22`，比如说
```
zuozhong "Ikarie XB 1 1963 1080p GBR Blu-ray AVC LPCM 2.0-RePoPo" 22
```

------

另外开个 Issue 就不要加称呼了吧
