### ISSUE TITLE
zuozhong命令有BUG

### ISSUE THREAD

**Issue by wqzvic88** [Aniverse/inexistence#45]
zuozhong命令偶尔会出现BUG, 不管是默认区块大小，还是指定区块大小，均会提示
“The piece length must be a number between 15 and 28”。

默认不是16M，也就是24么，那应该在15-28之间啊，应该不会报错啊。
我再指定22，也会报错，“The piece length must be a number between 15 and 28”。

具体错误信息如下图：

[https://i.loli.net/2019/06/24/5d1042714433f34213.png](url)

**Comment by Rhilip** [comment]
文件名没有用引号引起来，或者空格没有转义。
你的问题，不是脚本的事
