### ISSUE TITLE
php7.2-mcrypt not found, skipping

### ISSUE THREAD

**Issue by parker-wang** [Aniverse/inexistence#46]
在安装过程中出现php7.2-mcrypt not found, skipping
，脚本安装最终会失败

**Comment by Aniverse** [comment]
更完整的日志有没有

**Comment by parker-wang** [comment]
没有已经重装系统，当时用的系统是Ubuntu18.04,后来改用纯净版Debian9 就没事

**Comment by Aniverse** [comment]
我自己在常用的 Hetzner、Online (包括 OneProvider Paris)、OVH 的 Ubuntu 18.04 上都没碰到过此类问题，不知道你用的是什么

主要是没有日志我无法判断

**Comment by parker-wang** [comment]
kimsufi 的ks3,cpu 是j1900

**Comment by Aniverse** [comment]
KS3 现在都能开到 J1900 了啊……比 N2800 强多了。

KS 的系统模板估计和 OVH 一样？OVH 的机器之前有人是 xmlrpc 编译不上，svn 下源码下不下来，后来我修了下测试了几次都没问题了（那人是 Debian 9）
不过最近 18.04 的 OVH 我是没测试过（72T 时候试的，不过由于 rtinst 部分基本不动所以除非 OVH 改了什么不然我觉得应该没什么影响），不知道 OVH VPS 的能不能做参考，哪天试试

**Comment by parker-wang** [comment]
看了网上说的，PHP7.2已经不支持mcrypt，可能是下的php版本高的原因

**Comment by Aniverse** [comment]
但是我自己别的系统用 Ubuntu 18.04 不照样没事，并且 php 和 rtorrent 本身应该没多大关系

**Comment by parker-wang** [comment]
那就不是太清楚了，反正现在能用了就不管了
