### ISSUE TITLE
qBittorrent 始终安装不成功

### ISSUE THREAD

**Issue by cokan** [Aniverse/inexistence#47]
Cloning into 'qBittorrent-4.1.6'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
/dev/fd/63: line 1877: cd: qBittorrent-4.1.6: No such file or directory
fatal: Not a git repository (or any of the parent directories): .git
/dev/fd/63: line 1901: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.

checkinstall 1.6.2, Copyright 2009 Felipe Eduardo Sanchez Diaz Duran
           This software is released under the GNU GPL.
*****************************************
**** Debian package creation selected ***
*****************************************

This package will be built according to these values: 

0 -  Maintainer: [ root@ubuntu]
1 -  Summary: [ qBittorrent BitTorrent client headless (qbittorrent-nox) ]
2 -  Name:    [ qbittorrent-nox ]
3 -  Version: [ 4.1.6 ]
4 -  Release: [ 1 ]
5 -  License: [ GPL ]
6 -  Group:   [ qbittorrent ]
7 -  Architecture: [ amd64 ]
8 -  Source location: [ source ]
9 -  Alternate source location: [  ]
10 - Requires: [  ]
11 - Provides: [ qbittorrent-nox ]
12 - Conflicts: [  ]
13 - Replaces: [  ]

Enter a number to change any of them or press ENTER to continue: 

Installing with make install...

========================= Installation results ===========================
make: *** No rule to make target 'install'.  Stop.

****  Installation failed. Aborting package creation.

Cleaning up...OK

Bye.

mv: cannot stat 'qbittorrent*deb': No such file or directory

**Comment by Rhilip** [comment]
看起来是你网络有问题，连安装包都没能下载下来

**Comment by cokan** [comment]
> 看起来是你网络有问题，连安装包都没能下载下来
有时候能成功 下载东西都没问题- -！

**Comment by Aniverse** [comment]
git clone 时遇到的问题（我自己从来没碰到过）
百度了下，试试看这个：https://www.cnblogs.com/zjfjava/p/10392150.html

操作完了以后再试下这一句：
```
git clone --depth=1 -b release-4.1.6 https://github.com/qbittorrent/qBittorrent
```
如果没报错的话，那脚本应该能够正常运行了

**Comment by cokan** [comment]
git clone --depth=1 -b release-4.1.6 https://github.com/qbittorrent/qBittorrent

**Comment by cokan** [comment]
qbittorrent/qBittorrent
Cloning into 'qBittorrent'...
remote: Enumerating objects: 1240, done.
remote: Counting objects: 100% (1240/1240), done.
remote: Compressing objects: 100% (1087/1087), done.
remote: Total 1240 (delta 380), reused 638 (delta 119), pack-reused 0
Receiving objects: 100% (1240/1240), 6.15 MiB | 9.00 KiB/s, done.
Resolving deltas: 100% (380/380), done.
Note: checking out 'ea7e47d11328f408ba435bafaf618b483851c651'.

**Comment by Aniverse** [comment]
现在你再去装脚本应该没问题了
