### ISSUE TITLE
请问如何更新qb版本？

### ISSUE THREAD

**Issue by JackZhangCHN** [Aniverse/inexistence#49]
请问如何更新qb从4.1.5到4.1.6？希望大佬可以回答下

**Comment by Aniverse** [comment]
刚看到这个 issue orz

`bash <(wget -qO- https://github.com/Aniverse/inexistence/raw/separate-script/00.Installation/package/qbittorrent/install) -v 4.1.6`

不一定能成，这个还在测试阶段

**Comment by PS0123456** [comment]
> 刚看到这个 issue orz
> 
> `bash <(wget -qO- https://github.com/Aniverse/inexistence/raw/separate-script/00.Installation/package/qbittorrent/install) -v 4.1.6`
> 
> 不一定能成，这个还在测试阶段

您好，QB4.1.7，不知道您有没有用qb。设置里面为什么没有高级设置？
我添加50+ Trackers后，但每个新任务仅启动1个Trackers（除BT种子自带外），应该是没在高级设置里面“打开允许同级tracker汇报选项”

**Comment by Aniverse** [comment]
> > 刚看到这个 issue orz
> > `bash <(wget -qO- https://github.com/Aniverse/inexistence/raw/separate-script/00.Installation/package/qbittorrent/install) -v 4.1.6`
> > 不一定能成，这个还在测试阶段
> 
> 您好，QB4.1.7，不知道您有没有用qb。设置里面为什么没有高级设置？
> 我添加50+ Trackers后，但每个新任务仅启动1个Trackers（除BT种子自带外），应该是没在高级设置里面“打开允许同级tracker汇报选项”

qBittorrent 4.1.7 这个版本的 **WebUI** 本来就***没有***  高级设置。  
目前没有任何稳定版的 qBittorrent WebUI 带有高级设置，还在开发阶段的 4.2.0 里倒是有。  

不过你可以加入这类参数到配置文件（`/home/username/.config/qBittorrent/qBittorrent.conf`）里：
```
Advanced\AnnounceToAllTrackers=true
# 总是向同级的所有 trackers 发布
Session\AnnounceToAllTiers=true
# 总是向所有等级的 trackers 发布
```

**Comment by PS0123456** [comment]
> > > 刚看到这个 issue orz
> > > `bash <(wget -qO- https://github.com/Aniverse/inexistence/raw/separate-script/00.Installation/package/qbittorrent/install) -v 4.1.6`
> > > 不一定能成，这个还在测试阶段
> > 
> > 
> > 您好，QB4.1.7，不知道您有没有用qb。设置里面为什么没有高级设置？
> > 我添加50+ Trackers后，但每个新任务仅启动1个Trackers（除BT种子自带外），应该是没在高级设置里面“打开允许同级tracker汇报选项”
> 
> qBittorrent 4.1.7 这个版本的 **WebUI** 本来就_**没有**_ 高级设置。
> 目前没有任何稳定版的 qBittorrent WebUI 带有高级设置，还在开发阶段的 4.2.0 里倒是有。
> 
> 不过你可以加入这类参数到配置文件（`/home/username/.config/qBittorrent/qBittorrent.conf`）里：
> 
> ```
> Advanced\AnnounceToAllTrackers=true
> # 总是向同级的所有 trackers 发布
> Session\AnnounceToAllTiers=true
> # 总是向所有等级的 trackers 发布
> ```

Thx. i will try these.
