### ISSUE TITLE
请问星大deluge的webui文件夹在什么位置？

### ISSUE THREAD

**Issue by Gurosuogen** [Aniverse/inexistence#5]
想用贴吧的那个汉化

**Comment by Aniverse** [comment]
apt 安装的（安装选项40或40）：
/usr/lib/python2.7/dist-packages/deluge/ui/web

从源码安装的（非40/50选项）：
/usr/lib/python2.7/dist-packages/deluge-版本号-py2.7.egg/deluge/ui/web

**Comment by Gurosuogen** [comment]
已解决，感谢。另外请问我装了qb和de还有flexget之后CPU常年占用50%内存用量比我另一台Quickbox还要多，请问这正常吗？服务器是ikoula的G3900

**Comment by Aniverse** [comment]
这得看你怎么用吧……不好说

**Comment by Gurosuogen** [comment]
除了flexget用cron设置了2分钟读取，别的都是默认设置。de1.3.15 qb4.10版本，选的都不是隐藏选项。

**Comment by Rhilip** [comment]
@Gurosuogen 建议使用top或htop命令看下是不是有其他程序占用CPU和Mem。。

**Comment by Gurosuogen** [comment]
PID   USER      PR  NI    VIRT    RES         SHR S  %CPU %MEM     TIME+ COMMAND                                                             
  563  root      20   0  932652 269944   8188  R  157.3       3.4   1258:01 qbittorrent-nox

渣U。。。
