### ISSUE TITLE
deluge web过于脆弱

### ISSUE THREAD

**Issue by tangyao-biu** [Aniverse/inexistence#50]
为什么qb的web那么坚挺，deluge的web也太脆弱了，各种掉线，假死，加载又慢，星大也喜欢用deluge，有什么解决方案吗？

**Comment by Aniverse** [comment]
（转为 QQ 讨论，故 close，以下为写给路过的人看的）

deluge 失联主要应该是 libtorrent-ratserbar 的锅，qbittorrent 用 libtorrent-ratserbar 1.1 也会出现反应慢或者失联的情况（但没 de 这么严重）。
另外失联的其实是 deluged，deluge-web 是连接 daemon 连不上（用其他手段也连不上 daemon，包括 Thin Client 和 deluge-console）
不算办法的解决办法——换 libtorrent-rasterbar 版本到 1.0.11，基本不会失联

此外失联大多数时候和系统负载高有关。比如说我一个盒子之前老失联，最近用加钱大法，多加了几块硬盘组 RAID0 后到目前为止没失联过 ←_←

**Comment by Jieoz** [comment]
> （转为 QQ 讨论，故 close，以下为写给路过的人看的）
> 
> deluge 失联主要应该是 libtorrent-ratserbar 的锅，qbittorrent 用 libtorrent-ratserbar 1.1 也会出现反应慢或者失联的情况（但没 de 这么严重）。
> 另外失联的其实是 deluged，deluge-web 是连接 daemon 连不上（用其他手段也连不上 daemon，包括 Thin Client 和 deluge-console）
> 不算办法的解决办法——换 libtorrent-rasterbar 版本到 1.0.11，基本不会失联
> 
> 此外失联大多数时候和系统负载高有关。比如说我一个盒子之前老失联，最近用加钱大法，多加了几块硬盘组 RAID0 后到目前为止没失联过 ←_←

怎么更换 libtorrent-rasterbar 版本到 1.0.11啊大佬。现在貌似没有自定义这个版本的选项
