### ISSUE TITLE
qb重启问题

### ISSUE THREAD

**Issue by deemoartisan** [Aniverse/inexistence#55]
大佬，qb在ssh用mingling重启的时候无论是ssh命令还是客户端控制，输入重启命令后web就打不开了。。。。。求问咋整

**Comment by Aniverse** [comment]
没碰到过。webui 打不开，你能确认下 qb 有没有在运行？
如果没在运行的话是个什么状态，以及自己手动以普通用户 ssh 输入 qbittorrent-nox 会有什么提示？
