### ISSUE TITLE
qb 4.2.0

### ISSUE THREAD

**Issue by deemoartisan** [Aniverse/inexistence#56]
大佬，啥时候支持qb4.2.0啊？如果需要自己手动更新的话应该怎么操作？自己编译安装呢？

**Comment by Aniverse** [comment]
不知道为毛我都看不到自己项目的 issue 提醒……

这个半年前 4.2.0 还没发布的时候就在准备，但是坑比较大做着做着就不想做了 (╯‵□′)╯︵┻━┻
当然最后这个肯定还是要做的，但是目前没有预计完成时间。

同理的还有 Deluge 2.0.3，也是要改的东西比较多做着做着就放弃治疗了

自己安装的话，如果你用的系统是 Ubuntu 18.04 或 Debian 10（不是这两个系统的话不行），你可以用 30 选项自定义版本号，输入 4.2.0 或者 4.2.1，按理来说应该能装上去
不过就算装上去了，目前也有两个问题：
1. WebUI 的密码不对，因为 qb 4.2.0 改了 webui 密码的加密方式。这个需要自己删除 qBittorrent.conf 里 WebUI 密码的字段，恢复到默认的密码后，登陆上后自己修改
目前 CLI 的解决办法是有了，不过其他部分没做完，单独把这个放上去，意义也不大
2. Flexget 2.X 版本不支持 qBittorrent 4.2.0+。需要 Flexget 3.X，而 3.X 需要 Python3 来装 flexget，脚本的 flexget 用的是 Python 2.7

至于 Debian 9 和 Ubuntu 16.04 这种老系统，装 qb 4.2.0+ 也不是不能装，但是会繁琐一些（需要自己想办法安装更高版本的 qt，直接 apt 装的没法用）

**Comment by deemoartisan** [comment]
> 不知道为毛我都看不到自己项目的 issue 提醒……
> 
> 这个半年前 4.2.0 还没发布的时候就在准备，但是坑比较大做着做着就不想做了 (╯‵□′)╯︵┻━┻
> 当然最后这个肯定还是要做的，但是目前没有预计完成时间。
> 
> 同理的还有 Deluge 2.0.3，也是要改的东西比较多做着做着就放弃治疗了
> 
> 自己安装的话，如果你用的系统是 Ubuntu 18.04 或 Debian 10（不是这两个系统的话不行），你可以用 30 选项自定义版本号，输入 4.2.0 或者 4.2.1，按理来说应该能装上去（我没测试过现在是否可行，以前 4.2.0 还处于测试版的时候是可以的）
> 不过就算装上去了，目前也有两个问题：
> 
> 1. WebUI 的密码不对，因为 qb 4.2.0 改了 webui 密码的加密方式。这个需要自己删除 qBittorrent.conf 里 WebUI 密码的字段，恢复到默认的密码后，登陆上后自己修改
>    目前 CLI 的解决办法是有了，不过其他部分没做完，单独把这个放上去，意义也不大
> 2. Flexget 2.X 版本不支持 qBittorrent 4.2.0+。需要 Flexget 3.X，而 3.X 需要 Python3 来装 flexget，脚本的 flexget 用的是 Python 2.7
>    这个的话脚本以后会用 Python3 的，自己重装下 flexget 也很简单
> 
> 至于 Debian 9 和 Ubuntu 16.04 这种老系统，装 qb 4.2.0+ 也不是不能装，但是会繁琐一些（需要自己想办法安装更高版本的 qt，直接 apt 装的没法用）
> 这个问题我在以后的脚本里会解决掉，不过这里就不说如何装了

感谢大佬，牛头啤酒送上

**Comment by Aniverse** [comment]
4.2.1 加上了
