### ISSUE TITLE
大佬可以方便更新一下libtorrent的版本吗

### ISSUE THREAD

**Issue by langren1353** [Aniverse/inexistence#57]
似乎现在已经是1.1.14的版本了2019年12月20日出来的，不知道大佬有没有时间搞一个出来呢
之前的1.1.13好像是2019年4月28出来的，不知道大佬有没有时间搞一个最新的出来呢

**Comment by Aniverse** [comment]
知道更新了，最近懒得弄。最主要是用起来也没啥区别

**Comment by Aniverse** [comment]
前阵子已更新
