### ISSUE TITLE
ikoula debian9 ipv6.sh安装无效

### ISSUE THREAD

**Issue by Sever-IO** [Aniverse/inexistence#58]
debian9，ikoula ipv6.sh旧脚本使用没问题，新版本安装后无效。

**Comment by Aniverse** [comment]
旧版本是指哪个版本？（或者说你之前使用没问题的时候是什么时间段运行的脚本？）
另外你是在同一台机器上测试的吗？
你之前标题是重启后失联，后来不失联了？

**Comment by Sever-IO** [comment]
大概15天前用脚本可以成功启用ipv6（因为注意到10天前ipv6,sh有过更新，所以称它为旧脚本），昨天同一台机器多次重装系统后都无法启用（脚本只安装了net-tools，再无反应），再执行脚本没有丝毫反应，手动重启后失联。因为期间尝试过手动修改interfaces，考虑到可能是我输入信息有误导致失联，所以划掉了失联。

**Comment by Aniverse** [comment]
ik 部分的代码我记得没动，把执行的逻辑 xjb 改了下，甚至我自己都没有测试过（懒），然后翻车了 233
迟点有空的话修复下

**Comment by Aniverse** [comment]
现在应该改好了，你可以再试下  
另外你可以试下不用加任何参数直接跑，我现在做了个交互菜单

**Comment by Aniverse** [comment]
新的 IPv6 脚本我放到另外一个项目上去了，本项目上的不怎么更新了（偶尔同步下）

```
bash <(wget -qO- https://github.com/Aniverse/aBox/raw/master/scripts/ipv6)
```

**Comment by Sever-IO** [comment]
非常感谢！
