### ISSUE TITLE
老大们，为什么qBittorrent和 Transmission只能下载没上传？

### ISSUE THREAD

**Issue by hzfa** [Aniverse/inexistence#59]
老大们，在谷歌云GCP创建好的，为什么qBittorrent和 Transmission都下载PT超快，上传却几乎没有是怎么回事啊？？

**Comment by Aniverse** [comment]
………………
要有上传，首先得有人从你这里下载

**Comment by hzfa** [comment]
> ………………
> 要有上传，首先得有人从你这里下载

不知是否另外需要在GCP里开UPNP或公网IP啥的，照理能下载就能通外网啊，估计是现在太早太少人下了吧- -！
不知在馒头这样挂上传会不会被封啊- -！

**Comment by Aniverse** [comment]
你要先搞清楚一点：你的下载有速度是因为你能连上别人，从别人那里下载。你有下载量，别人有上传量
现在你没有上传，你要先看，这个种子有没有除了你以外的人正在下载。如果没有，你上传给空气？
如果有，你得看看有几个人，如果只有几个人，你连不上或者连上了没速度那都是很正常的；如果有几百个人，你得看看别人的下载进度以及是否有做种人

PT 往往不是你下了你自己想看的电影还能顺便获得足够多的上传量。你要去下载那些新发布的、有大量人下载且没有几个人上传的种子（哪怕这个种子的资源你一点兴趣也没有），这样子才能获得更多的上传量
