### ISSUE TITLE
希望大佬添加卸载功能

### ISSUE THREAD

**Issue by colingpt** [Aniverse/inexistence#6]
脚本真的非常棒！重装机器后的神器，省事许多。

第一次用，一激动所有qb，rt，de，tr都装上了，后来发现，自己根本只用rt和qb，其他的就在那里占内存，希望大佬能够添加卸载软件的功能。

另外现在，mingling里只有关闭某个软件的选项，但没有卸载或者禁止自启动的选项，即使关闭后，下次重启，所有的软件又都出现了。。还得一个个的关闭。。。:cry:

再次感谢这么棒的脚本！

**Comment by Aniverse** [comment]
你说的这个卸载（卸载也没法做到和重装完一样那么干净，会有残留）和取消开机自启我是考虑过并且也打算做，不过优先级放在比较后边，什么时候做好就不好说了，几个月以后都有可能……
主要是我最近可能花在这方面的时间会越来越少（BTW 我现在自己手里一个盒子也没了，要测试的话都是开VPS测试……）

**Comment by Rhilip** [comment]
多数软件都是使用systemctl管理的，直接使用`systemctl disable <service_name>`，禁止开启启动即可。
比如`systemctl disable transmission-daemon`，就可以关闭tr的开启自启。。
——————
ps，注意使用root权限。。。还有其实软件空跑不占多少内存吧。。

**Comment by colingpt** [comment]
@Aniverse 感谢，就是提个建议，如果有机会能实现那是最好了。

@Rhilip 感谢指点，

```
sudo systemctl disable transmission
sudo systemctl disable deluge-web
sudo systemctl disable deluged
```

是可以用的，看了 /etc/systemd/system/multi-user.target.wants/下的文件，还有

```
sudo systemctl disable  transmission-daemon
sudo systemctl disable flexget
```

嗯，现阶段解决挺好。。。哈哈，重装太麻烦了，主要是还得重新导入各站rss。
