### ISSUE TITLE
flexget 配置问题

### ISSUE THREAD

**Issue by swvv** [Aniverse/inexistence#64]
<img width="651" alt="image" src="https://user-images.githubusercontent.com/25149246/81500689-70379880-9306-11ea-887f-0605e56528ab.png">
一键安装完之后 查看flexget状态，显示没有配置文件，gui连接不上，求解
<img width="482" alt="image" src="https://user-images.githubusercontent.com/25149246/81500736-a37a2780-9306-11ea-8c9e-6d98f00a753a.png">

**Comment by Aniverse** [comment]
root 下提示找不到配置文件，是因为 flexget 不是用 root 运行的，所以使用 root 账户输入相关命令会提示没有配置文件
配置文件在 /home/用户名/.config/flexget/config.yml

log 显示不出来是 flexget webui 的一个常见 bug，这个我没办法
