### ISSUE TITLE
如何安装deluge web ui

### ISSUE THREAD

**Issue by 1219099256** [Aniverse/inexistence#65]
我有一台ipv6-only的服务器，自己安装web ui无法访问，但是用这个脚本安装的就可以，因为硬盘太小我想自己装，大佬能否告知方法

**Comment by 1219099256** [comment]
我大概搜了一遍代码，好像是用了nginx反代

server
{
  listen 80;
  listen [::]:80;
  server_name [ip];

  location /deluge/
  {
    proxy_pass http://localhost:8112/;
    proxy_set_header X-Deluge-Base "/deluge/";
    add_header X-Frame-Options SAMEORIGIN;
  }
}
(不知道对不对)

但是连接不上

**Comment by Aniverse** [comment]
我脚本在这方面没什么特殊的处理，并且其实我并不懂 nginx 的配置，都是抄来的……
你用我脚本装的 deluge，http://[ipv6]:8112 我估计也是打不开的？然后 https:[ipv6]/deluge 这个可以打开，是这个意思么？
nginx 的配置除了反代部分以外我都是用的 rtinst 脚本的配置

**Comment by 1219099256** [comment]
> 我脚本在这方面没什么特殊的处理，并且其实我并不懂 nginx 的配置，都是抄来的……
> 你用我脚本装的 deluge，http://[ipv6]:8112 我估计也是打不开的？然后 https:[ipv6]/deluge 这个可以打开，是这个意思么？
> nginx 的配置除了反代部分以外我都是用的 rtinst 脚本的配置

是这个意思。您能不能把反代规则发一下

**Comment by Aniverse** [comment]
https://github.com/Aniverse/rtinst/blob/master/conf/reverse/deluge.conf
```
location /de {
    return 301 https://$host/deluge;
}

location /deluge {
    proxy_pass http://127.0.0.1:8112/;
    proxy_set_header X-Deluge-Base "/deluge/";
    include /etc/nginx/conf.d/proxy;
    add_header X-Frame-Options SAMEORIGIN;
}
```

**Comment by 1219099256** [comment]
> https://github.com/Aniverse/rtinst/blob/master/conf/reverse/deluge.conf
> 
> ```
> location /de {
>     return 301 https://$host/deluge;
> }
> 
> location /deluge {
>     proxy_pass http://127.0.0.1:8112/;
>     proxy_set_header X-Deluge-Base "/deluge/";
>     include /etc/nginx/conf.d/proxy;
>     add_header X-Frame-Options SAMEORIGIN;
> }
> ```
好的谢谢。我去研究一下

**Comment by Rhilip** [comment]
deluge web默认监听在 `0.0.0.0`上，也就是只监听ipv4。
你可以考虑在启动deluge web的时候手动传入 `-i ::/0`，将其监听在ipv6上。

参考：
https://github.com/deluge-torrent/deluge/blob/23a48dd01c86ef01cd1d13371de51247ec9a503b/deluge/ui/web/server.py#L56
https://github.com/deluge-torrent/deluge/blob/23a48dd01c86ef01cd1d13371de51247ec9a503b/deluge/ui/web/web.py#L33-L39

**Comment by 1219099256** [comment]
> deluge web默认监听在 `0.0.0.0`上，也就是只监听ipv4。
> 你可以考虑在启动deluge web的时候手动传入 `-i ::/0`，将其监听在ipv6上。
> 
> 参考：
> https://github.com/deluge-torrent/deluge/blob/23a48dd01c86ef01cd1d13371de51247ec9a503b/deluge/ui/web/server.py#L56
> https://github.com/deluge-torrent/deluge/blob/23a48dd01c86ef01cd1d13371de51247ec9a503b/deluge/ui/web/web.py#L33-L39
> 
> ```
> root@server:~# /usr/bin/python /usr/bin/deluge-web -h
> Usage: deluge-web [options] [actions]
> 
> Options:
>   -h, --help            show this help message and exit
>   -v, --version         Show program's version number and exit
> 
>   Common Options:
>     -c CONFIG, --config=CONFIG
>                         Set the config folder location
>     -l LOGFILE, --logfile=LOGFILE
>                         Output to designated logfile instead of stdout
>     -L LOGLEVEL, --loglevel=LOGLEVEL
>                         Set the log level: none, info, warning, error,
>                         critical, debug
>     -q, --quiet         Sets the log level to 'none', this is the same as `-L
>                         none`
> 
>   Web Options:
>     -b BASE, --base=BASE
>                         Set the base path that the ui is running on (proxying)
>     -f, --fork          Fork the web interface process into the background
>     -i INTERFACE, --interface=INTERFACE
>                         Binds the webserver to a specific IP address
>     -p PORT, --port=PORT
>                         Sets the port to be used for the webserver
>     --profile           Profile the web server code
>     --no-ssl            Forces the webserver to disable ssl
>     --ssl               Forces the webserver to use ssl
> ```

执行命令提示没有-i选项，才发现安装的版本是1.3.12，然后我又按照官网的方法安装，结果提示需要python3-libtorrent 1.1.1但提示最新版本只有1.0.7

**Comment by Aniverse** [comment]
> 执行命令提示没有-i选项，才发现安装的版本是1.3.12，然后我又按照官网的方法安装，结果提示需要python3-libtorrent 1.1.1但提示最新版本只有1.0.7

Deluge 1.3.12 和 libtorrent 1.0.7 是 Ubuntu 16.04 系统自带的版本，1.1.1 是 Debian 9 自带的版本，你是不是把系统的镜像源搞乱了？
libtorrent 的版本对于 deluge 和 qBittorrent 很重要，我目前建议使用 libtorrent 1.1.14（1.0.7 和 1.1.1 都有我个人认为比较影响使用的 bug），安装方式么自己编译，或者你可以使用 efs 的 deb 包来快速安装。至于 Deluge 自己从源码安装就行

**Comment by Rhilip** [comment]
看了下 `--interface` 特性是在1.3.14引入的
https://github.com/deluge-torrent/deluge/blob/deluge-1.3.14/ChangeLog#L16

**Comment by xq1360900379** [comment]
--interface="::"
这个参数的确可以直接使用，而且亲测有效果，我是在容器里面改的执行脚本
