### ISSUE TITLE
宝塔面板支持

### ISSUE THREAD

**Issue by zhuanyessr** [Aniverse/inexistence#70]
请问可以支持宝塔面板吗？这样可以兼顾文件管理，pt/bt下载后的文件,可以做http直链分发文件防盗链之类的，谢谢

**Comment by Aniverse** [comment]
rTorrent 目前使用 rtinst，以后重写 rt 的安装的话（这个事情我两年前就有计划，然而到现在都还没提上日程，所以不要有什么指望）我会设计成可以选择不装 nginx，这样子也不冲突。

但是就目前而言，你不装 rTorrent 的话和宝塔不冲突，装了的话冲突。我在短期内没有改这方面设定的打算。

**Comment by zhuanyessr** [comment]
恩，感谢大佬回复，测试在centos系统，和APPnode面板可以完美兼容运行，大佬，您有计划维护cengtos系统吗?谢谢

**Comment by Aniverse** [comment]
没有 CentOS 的计划，以后也不会有
1：我写脚本首先是满足自己需求，而我不使用 CentOS
2：我目前脚本上待填的坑都填不完，哪还有精力去适配 CentOS

主流的 seedbox 脚本里没有一个适配 CentOS 的。要么自己写脚本、要么手动装、要么用 Docker——或者不要用 CentOS。
