### ISSUE TITLE
脚本如何卸载

### ISSUE THREAD

**Issue by ownerowner** [Aniverse/inexistence#71]
根据脚本搭建了盒子，也设置了账号密码，但是第二次使用脚本重新搭建的时候用的新的账号密码，和第一次不一样，登录新的账号密码提示错误，只能登录初始设置的账号密码才能进去，不知道原因是什么

请问那个命令行如何才能进去，打什么代码，萌新一枚，望大佬赐教

**Comment by Aniverse** [comment]
简单来说的话——重装系统吧。
复杂点的话，往下看：

首先是 README：https://github.com/Aniverse/inexistence#notes
> 目前没有简单易用的卸载方法。如果你有卸载的需求，使用前请三思

脚本在设计之初 **完全** 没有考虑过卸载的问题（因为我自己基本上没有这个需求，我写脚本首先是满足自己的需求，其次才是别人的需求），我个人的解决办法就是直接重装系统。卸载的功能以后会做，但是这个功能我给的优先级很低。
顺带一提，很多 seedbox 类脚本都没有提供卸载功能，或者无法卸载整个脚本（但可以卸载某些软件）

两次安装使用不同的账号密码——至于这点：
1、我在一定程度上有考虑过这个场合，做了一定的处理，但是没怎么测试过，所以具体表现如何我也不清楚。我要说明的一点是：这个脚本不是为了这个用法而设计的。换言之，两次运行脚本使用不同的账号密码，对我来说就是一种错误的用法。
这个脚本本身在设计的时候是单用户脚本，现在有一定程度上的多用户设计，但是本质上还是个单用户脚本。如果你要多用户脚本，请使用 swizzin（但是 swizzin 也不是让你跑两次 swizzin 来添加第二个用户的）
2、不同软件在这方面也会有所不同，所以你只说登陆新的账号密码提示错误，我不知道你无法登陆的是 rtorrent 还是 deluge 还是 qbittorrent 或者是别的什么，我无法做进一步的判断
