### ISSUE TITLE
星大脚本如何做种

### ISSUE THREAD

**Issue by Liusiyuan666** [Aniverse/inexistence#72]
你好，星大，你这个脚本聚体怎么做种啊，不明白

**Comment by Aniverse** [comment]
做种有两种理解：
1. 制作一个 torrent 文件
CLI 可以用过 mktorrent、transmission-create 等手段，WebUI 可以用 ruTorrent，GUI 可以用 deluge thin client。具体使用方法请谷歌自行解决
2. 发布种子后或者辅种中的 seeding 行为
选择好文件保存目录，把种子添加到客户端，进行校验。校验到 100% 后即可开始做种

这些都属于使用层面的问题，和脚本本身无关。

**Comment by ownerowner** [comment]
> 做种有两种理解：
> 
> 1. 制作一个 torrent 文件
>    CLI 可以用过 mktorrent、transmission-create 等手段，WebUI 可以用 ruTorrent，GUI 可以用 deluge thin client。具体使用方法请谷歌自行解决
> 2. 发布种子后或者辅种中的 seeding 行为
>    选择好文件保存目录，把种子添加到客户端，进行校验。校验到 100% 后即可开始做种
> 
> 这些都属于使用层面的问题，和脚本本身无关。

请问一下作者，那个命令行做种和mktorrent做种命令行没有太大区别吧，-p -a -o -d 之类的代码能在zuozhong命令里使用吧

**Comment by Aniverse** [comment]
> > 做种有两种理解：
> > 
> > 1. 制作一个 torrent 文件
> >    CLI 可以用过 mktorrent、transmission-create 等手段，WebUI 可以用 ruTorrent，GUI 可以用 deluge thin client。具体使用方法请谷歌自行解决
> > 2. 发布种子后或者辅种中的 seeding 行为
> >    选择好文件保存目录，把种子添加到客户端，进行校验。校验到 100% 后即可开始做种
> > 
> > 这些都属于使用层面的问题，和脚本本身无关。
> 
> 请问一下作者，那个命令行做种和mktorrent做种命令行没有太大区别吧，-p -a -o -d 之类的代码能在zuozhong命令里使用吧

你要用这类参数就用 mktorrent 就行了，zuozhong 就是把一堆参数写死让它用起来更简单一点而已。你需要自定义的话直接用 mktorrent
