### ISSUE TITLE
rutorrent無法更改預設下載路徑

### ISSUE THREAD

**Issue by tpa** [Aniverse/inexistence#76]
有確定目錄都有掛載了，但更改成/mnt/poan2或/mnt/poan3都不行
都會變成預設的路徑/home/poan/rtorrent/download
![Image of path](https://i.imgur.com/pRGyCgC.png)

**Comment by Aniverse** [comment]
你是怎么改下载路径的？改 rtorrent.rc 么？
另外你设定的这个下载路径，rtorrent 的用户是否有足够的权限？

**Comment by tpa** [comment]
1.改webui的下載路徑和rtorrent.rc好像都不行
我是改sudo nano /home/poan/inexistence/config/rtorrent.rc 
           directory.default.set = (cat,(cfg.basedir),"download") 
把()裡面改成 ->directory.default.set = (/mnt/poan2/) 
2.可能是權限問題，可以請教大大權限要怎麼設定嗎？感謝您

**Comment by tpa** [comment]
大佬我後來用你的一鍵安裝系統，問題算解決了，他幫我自動分配好空間不用另外移動了
感謝您
![new](https://i.imgur.com/NJ63qKw.png)
