### ISSUE TITLE
大佬，无法安装脚本，Too simple! Only x86_64 is supported。

### ISSUE THREAD

**Issue by ywyha** [Aniverse/inexistence#81]
Excited! You're running this script as root. Let's make some big news ... 
Too simple! Only x86_64 is supported

可是我的CPU和系统都是x86_64，系统也是全新的环境

**Comment by ywyha** [comment]
又重装了一下，依然不行，CPU是C2338

**Comment by ywyha** [comment]
系统是debian9，重装了两次系统，依然上述提示

**Comment by pengkaiwei** [comment]
安装curl

**Comment by ywyha** [comment]
> 安装curl

谢谢，已解决……这个问题都困扰很久了…… 希望星大出个判定……要不小白真不知道咋回事……

**Comment by pengkaiwei** [comment]
> > 安装curl
> 
> 谢谢，已解决……这个问题都困扰很久了…… 希望星大出个判定……要不小白真不知道咋回事……

我也是试了很多~最后搜到你这个了，顺便提醒一下

**Comment by ywyha** [comment]
> > > 安装curl
> > 
> > 
> > 谢谢，已解决……这个问题都困扰很久了…… 希望星大出个判定……要不小白真不知道咋回事……
> 
> 我也是试了很多~最后搜到你这个了，顺便提醒一下

太感谢了，之前都放弃debian了，还好碰到了你，吼吼~

**Comment by Aniverse** [comment]
基本弃坑的我也懒得研究到底哪里出了 bug 导致没有判断出 arch……
现在简单粗暴的多加了一个判定和错误提示，应该能在一定程度上解决这个问题
