### ISSUE TITLE
能否增加qBittorrent Enhanced Edition的版本

### ISSUE THREAD

**Issue by kettly1260** [Aniverse/inexistence#82]
qBittorrent Enhanced Edition具有反吸血和更新trackerlist的功能，比原版的qBittorrent要好用一些

**Comment by Aniverse** [comment]
过了快半年了我才来回复，抱歉。
我基本是个弃坑咸鱼了，再加上这个脚本主要面向 PT 用户，因此目前不考虑加入 qbee。
但在本脚本的基础上安装 qbee 也很简单（主要是因为 qbee 官方提供了静态编译）

首先使用本脚本随便安装一个 官方版 qBittorrent，然后：
```
wget https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-4.3.6.10/qbittorrent-nox_x86_64-linux-musl_static.zip
unzip qbittorrent-nox_x86_64-linux-musl_static.zip && rm qbittorrent-nox_x86_64-linux-musl_static.zip
cp -f ./qbittorrent-nox /usr/bin/qbittorrent-nox
chmod +x /usr/bin/qbittorrent-nox
```
这就把原版  qBittorrent 替换为了 qBittorrent Enhanced Edition，然后使用 `qqbb r` 重启就可以了
