### ISSUE TITLE
mingling 03查看系统信息中硬盘大小不正确

### ISSUE THREAD

**Issue by Magic-glass** [Aniverse/inexistence#85]
![UZ@T L85I4IX QE8E_OTUAW](https://user-images.githubusercontent.com/49303407/109000627-e9aa4700-76de-11eb-9f51-51dfc5cd004f.png)
实际上硬盘大小为700g
![2{_X3)$L70 EDTS3U088T4N](https://user-images.githubusercontent.com/49303407/109000680-fe86da80-76de-11eb-9b1f-1f3ec81813f1.png)
猜测是因为把docker的overlay也计算入内了？

>  00.Installation/check-sys 
> `131.disk_size1=($( LANG=C df -hPl | grep -wvE '\-|none|tmpfs|devtmpfs|by-uuid|chroot|Filesystem' | awk '{print $2}' ))`

萌新一个，劳烦dalao了

**Comment by RtYkk** [comment]
https://github.com/Aniverse/inexistence#mingling
![chrome_mkonVD7znA](https://user-images.githubusercontent.com/45971730/109374306-5136e100-78ef-11eb-94a7-964474e71764.png)

> 这个脚本我基本放弃治疗的，很少更新，会有过时的问题

我恐怕不会修，建议切换到 [Aniverse/A](https://github.com/Aniverse/A)
