### ISSUE TITLE
Flexget webui默认端口被chrome屏蔽

### ISSUE THREAD

**Issue by hlc1209** [Aniverse/inexistence#88]
Flexget webui默认端口6566被chrome/firefox屏蔽，报错为ERR_UNSAFE_PORT。
麻烦大佬改一个默认端口

**Comment by Magic-glass** [comment]
如果你安装了mingling
使用`fgs`可以访问配置文件
你也可以直接访问`~/.config/flexget/config.yml`
```
web_server: 
  port:             #修改为你需要的端口
```

**Comment by Easy0Fame** [comment]
> 如果你安装了mingling
> 使用`fgs`可以访问配置文件
> 你也可以直接访问`~/.config/flexget/config.yml`
> 
> ```
> web_server: 
>   port:             #修改为你需要的端口
> ```

没有flexget目录怎么办？

**Comment by hlc1209** [comment]
说明你的flexget没安装成功

**Comment by Aniverse** [comment]
现在脚本的 FlexGet WebUI 端口号已改为 9566，之前安装的可以使用如下命令修改：
```
source /etc/inexistence/00.Installation/function
export_inexistence_info
sed -i "s|6566|9566|" /home/$iUser/.config/flexget/config.yml
systemctl restart flexget@$iUser
```
