### ISSUE TITLE
OneProvider ipv6的问题

### ISSUE THREAD

**Issue by BenZinaDaze** [Aniverse/inexistence#9]
OneProvider 独服ipv6配置好像有一点不同
`/etc/network/interfaces` 这个文件中
`address 2001:xxx:xxxx:xxxx::`
直接这样写是不行的，最后会配置失败
应该在后面加一个1
例如
`address 2001:xxx:xxxx:xxxx::1`
这样才配置成功

不知道是不是OneProvider 有点特殊
其他完全没问题

**Comment by Aniverse** [comment]
我自己最常用的盒子就是 OneProvider 法国巴黎（OP 巴黎机房的独服都是 Online 的）的独服，没碰到你说的这个问题，我的地址写的就是你说的 `2001:xxx:xxxx:xxxx::` 这样的

用自己这个脚本在一些 Online Store-1-S（即 ST8）、Pro-1-S-SATA（俗称 20欧4T特价机，E3 1220 4TB）、Pro-2-S（俗称 17欧特价机，E3 1230 V2）、Dedibox-DC-DELL（俗称 OP 10欧/15欧标配，i3 530/540）、Dedibox-DC-HP（俗称 OP 10欧/15欧高配，i3 2100）、Start-2-M-SSD（俗称 16欧）、Start-2-S-SATA（俗称 9欧）、Start-1-M-SATA（俗称7欧） 测试过都没有问题

至于非 Online／OneProvider 的独服我就没试过了
