### ISSUE TITLE
libtorrent版本选择

### ISSUE THREAD

**Issue by Easy0Fame** [Aniverse/inexistence#92]
新版本的libtorrent下载链接：https://github.com/arvidn/libtorrent/releases/download/v1.2.14/libtorrent-rasterbar-1.2.14.tar.gz
旧版本的libtorrent下载链接：https://github.com/arvidn/libtorrent/releases/download/libtorrent-1.2.10/libtorrent-rasterbar-1.2.10.tar.gz
更旧版本的libtorrent下载链接：https://github.com/arvidn/libtorrent/releases/download/libtorrent-1_1_14/libtorrent-rasterbar-1.1.14.tar.gz
倒数前一级目录不一样导致选择新版本时出现错误，可否修复一下

**Comment by Aniverse** [comment]
抱歉，libtorrent 版本选择的问题我已经放弃治疗了……
