### ISSUE TITLE
安装rTorrent会卡checking，flexget webui 6566端口浏览器会屏蔽

### ISSUE THREAD

**Issue by softshield** [Aniverse/inexistence#93]
ubuntu 18.4，选择安装rtorrent 会卡cheking：

 

> Checking major 3rd party components
> Rtorrent:

然后就一直卡住不动了，也没提示。

**Comment by GoDKyLiN** [comment]
请问您的问题解决了吗？能否麻烦您分享一下解决办法。

**Comment by Aniverse** [comment]
rtorrent 官网最近抽风……我刚才简单粗暴地改了下，应该能用了

FlexGet WebUI 端口号已改为 9566，之前安装的可以使用如下命令修改：
```
. s-alias
source /etc/inexistence/00.Installation/function
export_inexistence_info
sed -i "s|9566|9567|" /home/$iUser/.config/flexget/config.yml
systemctl restart flexget@$iUser
```
