### ISSUE TITLE
無法安裝rtorrent

### ISSUE THREAD

**Issue by Laputa-Skywalker** [Aniverse/inexistence#94]
Checking major 3rd party components
Rtorrent: FAIL
xmlrpc-c: OK
RuTorrent: OK
Autodl-irssi: OK
Some of the repositories we need are not currently available.
We will continue for now, but may not be able to finish
You can rerun rtinst later to complete the installation if needed

**Comment by Aniverse** [comment]
rTorrent 官网最近时常抽风的样子，我简单粗暴地绕过去了（个别情况下会存在 bug，但 99.9% 的人应该不会碰到），现在应该好了
