### ISSUE TITLE
不支持debian11 系统

### ISSUE THREAD

**Issue by linjialaowang** [Aniverse/inexistence#95]
使用debian11 安装脚本会报错，提示系统版本过低，望修复

**Comment by Aniverse** [comment]
不算是 bug。  
如 README 所说，这个脚本仅支持 Debian 9/10 和 Ubuntu 16.04/18.04，我也懒得支持 Debian 11 和 Ubuntu 20.04 了。  
现在我基本弃坑了，除非有影响使用的 bug 不然我是懒得动了
